language: java
sudo: false
dist: trusty


addons:
    sonarcloud:
        organization: "artsok-github"
        token:
            secure: $SONAR_TOKEN

jdk:
- oraclejdk8

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start &
    - sleep 3

script:
    - mvn test sonar:sonar
    - bash <(curl -s https://codecov.io/bash)
