language: java
sudo: false
dist: trusty


addons:
    sonarcloud:
        organization: "artsok-github"
        token:
            secure: "AJlLVjNUiwOBK0AgSPgGyDotWYZjg07G2hS68ygupFCDPNsJJC8wNmJIOKy8PGMEX2zJ1LdA0ou/nbyp+zyhLykLauXSwhgwuOZN7gkb7CF3otd5Ae3EQRYXIDRbbCr8hmqkovnZGe3MQRi6BxZEemMkZQd/P0dGT36PBzKdPYSTMqzd0AEwpFHffyPQ/vgPArgNVQaNpEHhrkptg0uQTFXmiFaUoXROrUyCazavQdp534KwVFBWJowerOZVh6NjSESChYWyyPtkLnDuCKy7E+bQpaZtPIC5TOg3hOjBM31+dnszkWAp/sFr0rCNuN/wcUjvI13ssXYRCOanXok79+ctmZb0N/VV1tKhYvwVdgFNDLWbi5PBkYtrTzplN9YhZV4vBjoRDw4RTvtAD21OwkXifRp+JBHK8Lw8EwQa0ttDErf7NLmydrgFV9iZZWV7cA5gANXxwPByzAKP2/oLcbYuCKyPzsy6l+reGe3GJ9/9rjHNDmjkEHSO09ZF3lMU4qysmXH4qCZvnWWkWrm6RUzKzZgR0LX6AfFpMuMTZqm9lOCFycXGjr8Dw7/IfODL59ztoUuNLtnnUKiHg2psC5EM4oDzTxrQpoQfC8yxV0muoUIbS7XbXtwcKQkMxr8EmhlzvsGMarXqubqLOYlc/MSvR25y4CnzyCaZDbbbxFs="

jdk:
- oraclejdk8

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start &
    - sleep 3

script:
    - mvn test sonar:sonar
    - bash <(curl -s https://codecov.io/bash)
